comida(manzana,vitamina_B).
comida(manzana, vitamina_C).
comida(manzana, fibra).
comida(manzana, antioxidante).
comida(naranja, vitamina_C).
comida(naranja, antioxidante).
comida(platano, potasio).
comida(platano, vitamina_B6).
comida(espinaca, hierro).
comida(espinaca, vitamina_K).
comida(espinaca, vitamina_A).
comida(brócoli, vitamina_C).
comida(brócoli, vitamina_K).
comida(brócoli, fibra).
comida(arandanos, antioxidante).
comida(arandanos, vitamina_C).
comida(arandanos, vitamina_K).
comida(salmón, ácidos_grasos_omega_3).
comida(salmón, proteína).
comida(salmón, vitamina_D).
