nutricion(vitamina_B, desgano).
nutricion(vitamina_B, fatiga).
nutricion(vitamina_B, irritabilidad).
nutricion(vitamina_C, debilidad).
nutricion(vitamina_C, dolor_articular).
nutricion(vitamina_C, piel_seca).
nutricion(hierro, fatiga).
nutricion(hierro, palidez).
nutricion(hierro, falta_de_concentracion).
nutricion(calcio, calambres_musculares).
nutricion(calcio, debilidad_osea).
nutricion(calcio, osteoporosis).
nutricion(omega_3, depresion).
nutricion(omega_3, ansiedad).
nutricion(omega_3, problemas_de_memoria).
nutricion(platos_suaves, dolor_al_tragar).
nutricion(yogurt, dolor_al_tragar).
nutricion(infusiones_tibias, dolor_al_tragar).
nutricion(frutas, cansancio_fatiga).
nutricion(verduras, cansancio_fatiga).
nutricion(nueces, cansancio_fatiga).
nutricion(platanos, cansancio_fatiga).
nutricion(aguacates, cansancio_fatiga).
nutricion(legumbres, cansancio_fatiga).
nutricion(yogurt, cansancio_fatiga).
nutricion(zumos_naranja_calcio, cansancio_fatiga).
nutricion(pan_tostado, nauseas_mareos).
nutricion(cereales, nauseas_mareos).
nutricion(jengibre_bebidas, nauseas_mareos).
nutricion(miel_bebidas, nauseas_mareos).
nutricion(alcohol, nauseas_mareos).
nutricion(cafeina, nauseas_mareos).
nutricion(platano, diarrea).
nutricion(pan_tostado, diarrea).
nutricion(arroz, diarrea).
nutricion(pollo_horno, diarrea).
nutricion(pavo_sinpiel, diarrea).
nutricion(chocolate, estrenimiento).
nutricion(lacteos, estrenimiento).
nutricion(sorbitol, estrenimiento).
nutricion(ciruelas_pasas, estrenimiento).
nutricion(brocoli, estrenimiento).
nutricion(peras, estrenimiento).
nutricion(manzanas, estrenimiento).
nutricion(omega3, rojeces_erupciones).
nutricion(proteinas, rojeces_erupciones).
nutricion(pescados_grasos, rojeces_erupciones).
nutricion(salmon, rojeces_erupciones).
nutricion(sardinas, rojeces_erupciones).
nutricion(aceite_lino, rojeces_erupciones).
nutricion(chocolate, nariz_taponada).
nutricion(alcohol, nariz_taponada).
nutricion(jengibre_curcuma, nariz_taponada).
nutricion(pimienta_negra, nariz_taponada).
nutricion(nariz_moqueante, nariz_taponada).
nutricion(jengibre_miel_limon, nariz_moqueante).
nutricion(cebolla, nariz_moqueante).
nutricion(manzanas, nariz_moqueante).
nutricion(brocoli, nariz_moqueante).
nutricion(alcohol, nariz_moqueante).
nutricion(nuez, dolor_cabeza).
nutricion(salmon, dolor_cabeza).
nutricion(sardinas, dolor_cabeza).
nutricion(aceite_lino, dolor_cabeza).
nutricion(chocolate, dolor_cabeza).
nutricion(salsa_soja, dolor_cabeza).
nutricion(higado_pollo, dolor_cabeza).
nutricion(pescados_grasos, dolor_cabeza).
nutricion(nuez, dolor_oido).
nutricion(salmon, dolor_oido).
nutricion(sardinas, dolor_oido).
nutricion(aceite_lino, dolor_oido).
nutricion(zumo_naranja, dolor_oido).
nutricion(vitamina_C, dolor_oido).
nutricion(agua, dolor_oido).
