nutricion(vitamina_B, desgano).
nutricion(vitamina_B, fatiga).
nutricion(vitamina_B, irritabilidad).
nutricion(vitamina_C, debilidad).
nutricion(vitamina_C, dolor_articular).
nutricion(vitamina_C, piel_seca).
nutricion(hierro, fatiga).
nutricion(hierro, palidez).
nutricion(hierro, falta_de_concentracion).
nutricion(calcio, calambres_musculares).
nutricion(calcio, debilidad_osea).
nutricion(calcio, osteoporosis).
nutricion(omega_3, depresion).
nutricion(omega_3, ansiedad).
nutricion(omega_3, problemas_de_memoria).
